"""Report tools — PDF intelligence report generation and Telegram delivery."""

import logging
import os
import time
from datetime import datetime

import requests

from charlie.config import settings
from charlie.tools.tool_decorator import tool, RiskTier

logger = logging.getLogger("charlie.tools.reports")

REPORTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "reports")


def _ensure_reports_dir():
    os.makedirs(REPORTS_DIR, exist_ok=True)


def _send_pdf_telegram(pdf_path: str, caption: str) -> bool:
    """Send a PDF file to Telegram as a document. Returns True on success."""
    token = settings.supervisor.telegram_token
    chat_id = settings.supervisor.telegram_chat_id
    if not token or not chat_id:
        logger.error("telegram_credentials_missing")
        return False

    url = f"https://api.telegram.org/bot{token}/sendDocument"
    logger.debug("pdf_telegram_send | url=https://api.telegram.org/bot[REDACTED]/sendDocument | chat_id=%s", chat_id)
    try:
        with open(pdf_path, "rb") as f:
            resp = requests.post(
                url,
                data={"chat_id": chat_id, "caption": caption, "parse_mode": "Markdown"},
                files={"document": f},
                timeout=30,
            )
        if resp.status_code == 200:
            logger.info("pdf_sent_telegram | path=%s", pdf_path)
            return True
        logger.error("telegram_send_failed | status=%d | %s", resp.status_code, resp.text[:200])
        return False
    except Exception as e:
        logger.error("telegram_send_error | %s", e)
        return False


def _build_pdf(data: dict, title: str, output_path: str) -> str:
    """Build a PDF report from structured data. Returns output path."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    doc = SimpleDocTemplate(output_path, pagesize=A4, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontSize=18,
        spaceAfter=6,
        textColor=colors.HexColor("#1a1a2e"),
    )
    subtitle_style = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.grey,
        spaceAfter=20,
    )
    heading_style = ParagraphStyle(
        "ReportHeading",
        parent=styles["Heading2"],
        fontSize=14,
        spaceBefore=16,
        spaceAfter=8,
        textColor=colors.HexColor("#16213e"),
    )
    body_style = ParagraphStyle(
        "ReportBody",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        spaceAfter=8,
    )

    story = []

    # Header
    story.append(Paragraph("CHARLIE Intelligence Report", title_style))
    story.append(Paragraph(f"{title} — {datetime.now().strftime('%Y-%m-%d %H:%M')}", subtitle_style))

    # Sections
    for section in data.get("sections", []):
        heading = section.get("heading", "")
        content = section.get("content", "")
        section_type = section.get("type", "text")

        if heading:
            story.append(Paragraph(heading, heading_style))

        if section_type == "text":
            story.append(Paragraph(str(content), body_style))

        elif section_type == "list":
            items = content if isinstance(content, list) else str(content).split("\n")
            for item in items:
                story.append(Paragraph(f"• {item}", body_style))

        elif section_type == "table":
            rows = content if isinstance(content, list) else []
            if rows:
                table = Table(rows, hAlign="LEFT")
                table.setStyle(
                    TableStyle(
                        [
                            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#16213e")),
                            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                            ("FONTSIZE", (0, 0), (-1, -1), 9),
                            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0f0f0")]),
                            ("PADDING", (0, 0), (-1, -1), 6),
                        ]
                    )
                )
                story.append(table)

        story.append(Spacer(1, 8))

    # Footer
    story.append(Spacer(1, 20))
    footer_style = ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey)
    story.append(Paragraph(f"Generated by CHARLIE — {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", footer_style))

    doc.build(story)
    return output_path


@tool(
    name="generate_intelligence_report",
    description="Generate a PDF intelligence report from structured data and send to Sir via Telegram. Data format: {'sections': [{'heading': str, 'content': str|list, 'type': 'text'|'list'|'table'}]}",
    category="reports",
    risk_tier=RiskTier.TIER_0,
)
def generate_intelligence_report(data: dict, title: str) -> str:
    _ensure_reports_dir()
    safe_title = "".join(c for c in title if c.isalnum() or c in " _-").strip().replace(" ", "_")
    filename = f"report_{safe_title}_{int(time.time())}.pdf"
    output_path = os.path.join(REPORTS_DIR, filename)

    try:
        _build_pdf(data, title, output_path)
        logger.info("pdf_generated | path=%s", output_path)
    except Exception as e:
        logger.error("pdf_generation_failed | %s", e)
        return f"PDF generation failed: {e}"

    caption = f"*{title}*\nIntelligence report — {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    sent = _send_pdf_telegram(output_path, caption)

    if sent:
        try:
            os.remove(output_path)
        except OSError:
            pass
        return f"Report '{title}' generated and delivered to Telegram, Sir."

    return f"Report '{title}' generated at {output_path} but Telegram delivery failed."


@tool(
    name="send_report_telegram",
    description="Send an existing PDF file to Sir via Telegram with a caption.",
    category="reports",
    risk_tier=RiskTier.TIER_0,
)
def send_report_telegram(pdf_path: str, caption: str) -> str:
    if not os.path.exists(pdf_path):
        return f"File not found: {pdf_path}"

    sent = _send_pdf_telegram(pdf_path, caption)
    if sent:
        return "Document delivered to Telegram, Sir."
    return "Telegram delivery failed. Check credentials and connectivity."
